//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowInk.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowInk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lightweight desktop overlay drawing tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About FlowInk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About FlowInk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply Current Style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplyCurrentStyle {
            get {
                return ResourceManager.GetString("ApplyCurrentStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FlowInk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Color... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChooseColor {
            get {
                return ResourceManager.GetString("ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Circle (Fill ON {0}% / Right-click for settings) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CircleFilledToolTipFormat {
            get {
                return ResourceManager.GetString("CircleFilledToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Circle (Fill OFF / Right-click for settings) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CircleNotFilledToolTip {
            get {
                return ResourceManager.GetString("CircleNotFilledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClickThrough に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClickThrough {
            get {
                return ResourceManager.GetString("ClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drawing is OFF. Turn it ON using the toolbar button or the hotkey. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClickThroughOffToast {
            get {
                return ResourceManager.GetString("ClickThroughOffToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #{0}{1}{2}{3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorDisplayOpaqueFormat {
            get {
                return ResourceManager.GetString("ColorDisplayOpaqueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #{0}{1}{2}{3} ({4}%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorDisplayWithAlphaFormat {
            get {
                return ResourceManager.GetString("ColorDisplayWithAlphaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Picker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color (Click to PresetColors, Double-click to edit current color) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorToolTip {
            get {
                return ResourceManager.GetString("ColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CurrentSettings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CurrentSettings {
            get {
                return ResourceManager.GetString("CurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current: 4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CurrentValueDefault {
            get {
                return ResourceManager.GetString("CurrentValueDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CurrentValueFormat {
            get {
                return ResourceManager.GetString("CurrentValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drawing is OFF. Press the OFF button or use the hotkey ({0}) to turn it ON. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawingDisabledToast {
            get {
                return ResourceManager.GetString("DrawingDisabledToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drawing is ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawingEnabledToast {
            get {
                return ResourceManager.GetString("DrawingEnabledToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawingOff {
            get {
                return ResourceManager.GetString("DrawingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawingOn {
            get {
                return ResourceManager.GetString("DrawingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle drawing ON/OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawingToolTip {
            get {
                return ResourceManager.GetString("DrawingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eraser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The global hotkey has been changed to {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GlobalHotkeyChangedFormat {
            get {
                return ResourceManager.GetString("GlobalHotkeyChangedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to register the global hotkey {0}.
        ///It may already be in use by another application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GlobalHotkeyRegisterFailedFormat {
            get {
                return ResourceManager.GetString("GlobalHotkeyRegisterFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hotkey に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hotkey {
            get {
                return ResourceManager.GetString("Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HotkeyModifierAlt {
            get {
                return ResourceManager.GetString("HotkeyModifierAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HotkeyModifierCtrl {
            get {
                return ResourceManager.GetString("HotkeyModifierCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HotkeyModifierShift {
            get {
                return ResourceManager.GetString("HotkeyModifierShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HotkeyModifierWin {
            get {
                return ResourceManager.GetString("HotkeyModifierWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lightweight overlay drawing tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LightweightOverlayDrawingTool {
            get {
                return ResourceManager.GetString("LightweightOverlayDrawingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FlowInk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drawing OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIconStatusOff {
            get {
                return ResourceManager.GetString("NotifyIconStatusOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drawing ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIconStatusOn {
            get {
                return ResourceManager.GetString("NotifyIconStatusOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not open the browser. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenBrowserFailed {
            get {
                return ResourceManager.GetString("OpenBrowserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pen (Right-click: Pen width settings) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenToolTip {
            get {
                return ResourceManager.GetString("PenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pen Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenWidth {
            get {
                return ResourceManager.GetString("PenWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pen Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenWidthDialogTitle {
            get {
                return ResourceManager.GetString("PenWidthDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   30 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenWidthMaxLabel {
            get {
                return ResourceManager.GetString("PenWidthMaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0.5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenWidthMinLabel {
            get {
                return ResourceManager.GetString("PenWidthMinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click: Select / Double-click: Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenWidthPresetItemToolTipSuffix {
            get {
                return ResourceManager.GetString("PenWidthPresetItemToolTipSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select pen width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenWidthSelectLabel {
            get {
                return ResourceManager.GetString("PenWidthSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click: Select / Double-click: Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PresetColorItemToolTipSuffix {
            get {
                return ResourceManager.GetString("PresetColorItemToolTipSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preset Colors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PresetColors {
            get {
                return ResourceManager.GetString("PresetColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Colors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecentColors {
            get {
                return ResourceManager.GetString("RecentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rectangle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rectangle (Fill ON {0}% / Right-click for settings) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RectangleFilledToolTipFormat {
            get {
                return ResourceManager.GetString("RectangleFilledToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rectangle (Fill OFF / Right-click for settings) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RectangleNotFilledToolTip {
            get {
                return ResourceManager.GetString("RectangleNotFilledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore Fill に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RestoreFill {
            get {
                return ResourceManager.GetString("RestoreFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select at least one modifier key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectAtLeastOneModifier {
            get {
                return ResourceManager.GetString("SelectAtLeastOneModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Line Thickness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectLineThickness {
            get {
                return ResourceManager.GetString("SelectLineThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsToolTip {
            get {
                return ResourceManager.GetString("SettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shape に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text (Double-click for font settings) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextToolTip {
            get {
                return ResourceManager.GetString("TextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transparency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transparency: {0}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransparencyFormat {
            get {
                return ResourceManager.GetString("TransparencyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransparencyMaxLabel {
            get {
                return ResourceManager.GetString("TransparencyMaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransparencyMinLabel {
            get {
                return ResourceManager.GetString("TransparencyMinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn Drawing OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrayMenuTurnDrawingOff {
            get {
                return ResourceManager.GetString("TrayMenuTurnDrawingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn Drawing ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrayMenuTurnDrawingOn {
            get {
                return ResourceManager.GetString("TrayMenuTurnDrawingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left click: Undo / Right click: Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndoRedoToolTip {
            get {
                return ResourceManager.GetString("UndoRedoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
    }
}
