//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowInk.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowInk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FlowInkについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   色を選ぶ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChooseColor {
            get {
                return ResourceManager.GetString("ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   円（塗りつぶしON {0}% / 右クリックで設定） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CircleFilledToolTipFormat {
            get {
                return ResourceManager.GetString("CircleFilledToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   円（塗りつぶしOFF / 右クリックで設定） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CircleNotFilledToolTip {
            get {
                return ResourceManager.GetString("CircleNotFilledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリック透過 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClickThrough {
            get {
                return ResourceManager.GetString("ClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画OFF。描画ONにするには、ツールバーのOFFボタンかホットキーを押してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClickThroughOffToast {
            get {
                return ResourceManager.GetString("ClickThroughOffToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #{0}{1}{2}{3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorDisplayOpaqueFormat {
            get {
                return ResourceManager.GetString("ColorDisplayOpaqueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #{0}{1}{2}{3} ({4}%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorDisplayWithAlphaFormat {
            get {
                return ResourceManager.GetString("ColorDisplayWithAlphaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラーピッカー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   色（クリックでプリセット色、ダブルクリックで現在色を編集） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorToolTip {
            get {
                return ResourceManager.GetString("ColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在の設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CurrentSettings {
            get {
                return ResourceManager.GetString("CurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CurrentValueFormat {
            get {
                return ResourceManager.GetString("CurrentValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画OFF。OFFボタンかホットキー({0})でONにできます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawingDisabledToast {
            get {
                return ResourceManager.GetString("DrawingDisabledToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawingEnabledToast {
            get {
                return ResourceManager.GetString("DrawingEnabledToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawingOff {
            get {
                return ResourceManager.GetString("DrawingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawingOn {
            get {
                return ResourceManager.GetString("DrawingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画ON/OFF切替 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DrawingToolTip {
            get {
                return ResourceManager.GetString("DrawingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消しゴム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   塗りつぶし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォントサイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グローバルホットキーを {0} に変更しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GlobalHotkeyChangedFormat {
            get {
                return ResourceManager.GetString("GlobalHotkeyChangedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グローバルホットキー {0} の登録に失敗しました。\n他のアプリで使われている可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GlobalHotkeyRegisterFailedFormat {
            get {
                return ResourceManager.GetString("GlobalHotkeyRegisterFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホットキー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hotkey {
            get {
                return ResourceManager.GetString("Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HotkeyModifierAlt {
            get {
                return ResourceManager.GetString("HotkeyModifierAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HotkeyModifierCtrl {
            get {
                return ResourceManager.GetString("HotkeyModifierCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HotkeyModifierShift {
            get {
                return ResourceManager.GetString("HotkeyModifierShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HotkeyModifierWin {
            get {
                return ResourceManager.GetString("HotkeyModifierWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lightweight overlay drawing tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LightweightOverlayDrawingTool {
            get {
                return ResourceManager.GetString("LightweightOverlayDrawingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIconStatusOff {
            get {
                return ResourceManager.GetString("NotifyIconStatusOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIconStatusOn {
            get {
                return ResourceManager.GetString("NotifyIconStatusOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不透明度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザを開けませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenBrowserFailed {
            get {
                return ResourceManager.GetString("OpenBrowserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ペン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ペン（右クリック: 線幅設定） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenToolTip {
            get {
                return ResourceManager.GetString("PenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   線幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenWidth {
            get {
                return ResourceManager.GetString("PenWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ペンの太さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenWidthDialogTitle {
            get {
                return ResourceManager.GetString("PenWidthDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   30 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenWidthMaxLabel {
            get {
                return ResourceManager.GetString("PenWidthMaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0.5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenWidthMinLabel {
            get {
                return ResourceManager.GetString("PenWidthMinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリック: 選択 / ダブルクリック: 編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenWidthPresetItemToolTipSuffix {
            get {
                return ResourceManager.GetString("PenWidthPresetItemToolTipSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   線の太さを選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PenWidthSelectLabel {
            get {
                return ResourceManager.GetString("PenWidthSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリック: 選択 / ダブルクリック: 編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PresetColorItemToolTipSuffix {
            get {
                return ResourceManager.GetString("PresetColorItemToolTipSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリセットカラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PresetColors {
            get {
                return ResourceManager.GetString("PresetColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最近使った色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecentColors {
            get {
                return ResourceManager.GetString("RecentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   四角 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   四角形（塗りつぶしON {0}% / 右クリックで設定） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RectangleFilledToolTipFormat {
            get {
                return ResourceManager.GetString("RectangleFilledToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   四角形（塗りつぶしOFF / 右クリックで設定） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RectangleNotFilledToolTip {
            get {
                return ResourceManager.GetString("RectangleNotFilledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーブ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   修飾キーを1つ以上選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectAtLeastOneModifier {
            get {
                return ResourceManager.GetString("SelectAtLeastOneModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   線の太さを選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectLineThickness {
            get {
                return ResourceManager.GetString("SelectLineThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsToolTip {
            get {
                return ResourceManager.GetString("SettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図形 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テキスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テキスト（ダブルクリックでフォント設定） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextToolTip {
            get {
                return ResourceManager.GetString("TextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   透明度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   透明度: {0}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransparencyFormat {
            get {
                return ResourceManager.GetString("TransparencyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画OFFにする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrayMenuTurnDrawingOff {
            get {
                return ResourceManager.GetString("TrayMenuTurnDrawingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画ONにする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrayMenuTurnDrawingOn {
            get {
                return ResourceManager.GetString("TrayMenuTurnDrawingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
    }
}
